#plots script for paper figures#
#you will need to have run the TSFP_FFP_calculations_script before running this one, as it uses datasets generated by that script#

#set working directory#
setwd("") #add working directory details here#

#add subdirectories#
dir.create("Results")
dir.create("Results/Figures_for_paper")
dir.create("Results/Stats")

#package loading#
library(tidyverse)
library(ggsci)
library(ggpubr)
library(vegan)


#data load#
reinf3_df <- read.csv("Results/FP_by_tissue/Reinf3_all_new_FP_data.csv")

#add tissue groups#
reinf3_df$INPUT3 <- reinf3_df$INPUT2
reinf3_df$INPUT3[reinf3_df$INPUT2 %in% c("SKIN01", "SKIN02", "SKIN03", "SKIN04", "SKIN05", "SKIN06", "SKIN07",
                                         "SKIN08", "SKIN09", "SKIN10", "SKIN11", "SKIN12")] <- "SKIN"
reinf3_df$INPUT3[reinf3_df$INPUT2 %in% c("BM1", "BM2")] <- "BM"
reinf3_df$INPUT3[reinf3_df$INPUT2 %in% c("LN1", "LN2")] <- "LN"
reinf3_df$INPUT3[reinf3_df$INPUT2 %in% c("LL", "LM", "LS")] <- "LIVER"

reinf3_df$OUTPUT3 <- reinf3_df$OUTPUT2
reinf3_df$OUTPUT3[reinf3_df$OUTPUT2 %in% c("SKIN01", "SKIN02", "SKIN03", "SKIN04", "SKIN05", "SKIN06", "SKIN07",
                                           "SKIN08", "SKIN09", "SKIN10", "SKIN11", "SKIN12")] <- "SKIN"
reinf3_df$OUTPUT3[reinf3_df$OUTPUT2 %in% c("BM1", "BM2")] <- "BM"
reinf3_df$OUTPUT3[reinf3_df$OUTPUT2 %in% c("LN1", "LN2")] <- "LN"
reinf3_df$OUTPUT3[reinf3_df$OUTPUT2 %in% c("LL", "LM", "LS")] <- "LIVER"                                  


#add animal groups#
#add groups#
reinf3_df$group <- NULL
reinf3_df$group[reinf3_df$mouse_ID %in% c("1", "2", "3", "4", "5")] <- "1single_04wk"
reinf3_df$group[reinf3_df$mouse_ID %in% c("12", "13", "14")] <- "1single_10wk"
reinf3_df$group[reinf3_df$mouse_ID %in% c("21", "22", "23", "24", "25")] <- "1single_12wk"
reinf3_df$group[reinf3_df$mouse_ID %in% c("15", "16", "17", "18", "19", "20")] <- "2reinf_2wk"
reinf3_df$group[reinf3_df$mouse_ID %in% c( "6", "7", "8", "9", "10", "11")] <- "2reinf_2d"

#add groups#
reinf3_df$group2 <- NULL
reinf3_df$group2[reinf3_df$mouse_ID %in% c("1", "2", "3", "4", "5")] <- "1single_early"
reinf3_df$group2[reinf3_df$mouse_ID %in% c("12", "13", "14")] <- "1single_late"
reinf3_df$group2[reinf3_df$mouse_ID %in% c("21", "22", "23", "24", "25")] <- "1single_late"
reinf3_df$group2[reinf3_df$mouse_ID %in% c("15", "16", "17", "18", "19", "20")] <- "2reinf_2wk"
reinf3_df$group2[reinf3_df$mouse_ID %in% c( "6", "7", "8", "9", "10", "11")] <- "2reinf_2d"


#plots#

#seeding from skin#

ggplot(subset(reinf3_df, INPUT2 != OUTPUT2 & group %in% c("1single_04wk", "1single_10wk", "1single_12wk") & INPUT3 %in% c("SKIN") & OUTPUT3 != c("SKIN")), 
       aes(y= FP, x = group2)) + 
  geom_jitter(aes(colour = group2, shape = as.factor(mouse_ID)),
              size = 1.5, stroke = 1,
              position = position_jitterdodge(dodge.width = .75, jitter.width = 0.1)) + 
  geom_boxplot(aes(fill = group2), alpha = 0.3,
               outlier.shape = NA, 
               width = 0.75, lwd = 0.8, fatten = 2, show.legend = FALSE) +
  scale_shape_manual(values = c(1, 2, 3, 4, 15, 16, 17, 18, 10,7,6, 8)) +
  labs(title = "Tissue-sourced seeding from skin\n", colour = "Infection phase:", x= "\nInfection phase", y = "TSFP\n") +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  #scale_x_discrete(expand = expansion(mult = c(0.15, 0))) +
  scale_x_discrete(labels = c("Early", "Chronic")) +
  theme_bw() + theme(legend.title = element_text(size = 18, hjust = 0.5),
                     plot.title = element_text(hjust = 0.5, size = 30),
                     legend.title.position = "top",
                     legend.position = "bottom",
                     panel.border = element_blank(), 
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     axis.title = element_text(size=28), 
                     axis.line = 
                       element_line(colour = "black"), 
                     axis.text.x = element_text(size = 20, hjust = 0.5, colour = "black"),
                     axis.text.y = element_text(size = 20, colour = "black"),
                     legend.text = element_text(size = 16, colour = "black"),
                     strip.text.x = element_text(size = 20)) +
  scale_fill_manual(values = c("#21918c", "#440154"), labels = c("Early", "Chronic")) +
  scale_colour_manual(values = c("#21918c", "#440154"), labels = c("Early", "Chronic"))+
  guides(fill="none", shape = "none") +
  facet_wrap(~OUTPUT3, nrow = 2, scales = "free", labeller = as_labeller(
    c(BM = "Bone Marrow", GUT = "Gut", LIVER = "Liver", LN =  "Lymph Node", LUNG = "Lung", S = "Spleen", SKIN = "Skin")))
ggsave(paste0(file = "Results/Figures_for_paper/reinf3_FP_by_tissue_skin_input_plot.png"), height = 10, width=8)
ggsave(paste0(file = "Results/Figures_for_paper/reinf3_FP_by_tissue_skin_input_plot.pdf"), height = 10, width=8)


#seeding to skin#

ggplot(subset(reinf3_df, INPUT2 != OUTPUT2 & group %in% c("1single_04wk", "1single_10wk", "1single_12wk") & OUTPUT3 %in% c("SKIN") & INPUT3 != c("SKIN")), 
       aes(y= FP, x = group2)) + 
  geom_jitter(aes(colour = group2, shape = as.factor(mouse_ID)),
              size = 1.5, stroke = 1,
              position = position_jitterdodge(dodge.width = .75, jitter.width = 0.1)) +
  scale_shape_manual(values = c(1, 2, 3, 4, 15, 16, 17, 18, 10,7,6, 8)) + 
  geom_boxplot(aes(fill = group2), alpha = 0.3,
               outlier.shape = NA, 
               width = 0.75, lwd = 0.8, fatten = 2, show.legend = FALSE) +
  labs(title = "Tissue-sourced seeding to skin\n", colour = "Infection phase:", x= "\nInfection phase", y = "TSFP\n") +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  #scale_x_discrete(expand = expansion(mult = c(0.15, 0))) +
  scale_x_discrete(labels = c("Early", "Chronic")) +
  theme_bw() + theme(legend.title = element_text(size = 18, hjust = 0.5),
                     plot.title = element_text(hjust = 0.5, size = 30),
                     legend.title.position = "top",
                     legend.position = "bottom",
                     panel.border = element_blank(), 
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     axis.title = element_text(size=28), 
                     axis.line = 
                       element_line(colour = "black"), 
                     axis.text.x = element_text(size = 20, hjust = 0.5, colour = "black"),
                     axis.text.y = element_text(size = 20, colour = "black"),
                     legend.text = element_text(size = 16, colour = "black"),
                     strip.text.x = element_text(size = 20)) +
  scale_fill_manual(values = c("#21918c", "#440154"), labels = c("Early", "Chronic")) +
  scale_colour_manual(values = c("#21918c", "#440154"), labels = c("Early", "Chronic"))+
  guides(fill="none", shape = "none") +
  facet_wrap(~INPUT3, nrow = 2, scales = "free", labeller = as_labeller(
    c(BM = "Bone Marrow", GUT = "Gut", LIVER = "Liver", LN =  "Lymph Node", LUNG = "Lung", S = "Spleen", SKIN = "Skin")))
ggsave(paste0(file = "Results/Figures_for_paper/reinf3_FP_by_tissue_skin_output_plot.png"), height = 10, width=8)
ggsave(paste0(file = "Results/Figures_for_paper/reinf3_FP_by_tissue_skin_output_plot.pdf"), height = 10, width=8)


#skin to skin seeding#
ggplot(subset(reinf3_df, INPUT2 != OUTPUT2 & group %in% c("1single_04wk", "1single_10wk", "1single_12wk") & INPUT3 %in% c("SKIN") & OUTPUT3 %in% c("SKIN")), 
       aes(y= FP, x = group2)) + 
  geom_jitter(aes(colour = group2, shape = as.factor(mouse_ID)),
              size = 1.5, stroke = 1,
              position = position_jitterdodge(dodge.width = .75, jitter.width = 0.1)) +
  scale_shape_manual(values = c(1, 2, 3, 4, 15, 16, 17, 18, 10,7,6, 8)) +
  labs(title = "Skin to skin seeding\n", colour = "Mouse:", x= "\nInfection phase", y = "TSFP\n") +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  #scale_x_discrete(expand = expansion(mult = c(0.15, 0))) +
  scale_x_discrete(labels = c("Early", "Chronic")) +
  theme_bw() + theme(legend.title = element_text(size = 18, hjust = 0.5),
                     plot.title = element_text(hjust = 0.5, size = 30),
                     legend.title.position = "top",
                     legend.position = "bottom",
                     panel.border = element_blank(), 
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     axis.title = element_text(size=28), 
                     axis.line = 
                       element_line(colour = "black"), 
                     axis.text.x = element_text(size = 20, hjust = 0.5, colour = "black"),
                     axis.text.y = element_text(size = 20, colour = "black"),
                     legend.text = element_text(size = 16, colour = "black"),
                     strip.text.x = element_text(size = 20)) +
  scale_fill_manual(values = c("#21918c", "#440154"), labels = c("Early", "Chronic")) +
  scale_colour_manual(values = c("#21918c", "#440154"), labels = c("Early", "Chronic"))+
  guides(fill="none", shape = "none") 
ggsave(paste0(file = "Results/Figures_for_paper/reinf3_FP_by_tissue_skin_to_skin_plot.png"), height = 6, width=6)
ggsave(paste0(file = "Results/Figures_for_paper/reinf3_FP_by_tissue_skin_to_skin_plot.pdf"), height = 6, width=6)

#mann whitney stats#

#supp table 8#
df_p_val <- subset(reinf3_df, INPUT2 != OUTPUT2 & group %in% c("1single_04wk", "1single_10wk", "1single_12wk")) %>%
  rstatix::group_by(OUTPUT3, INPUT3) %>% 
  rstatix::wilcox_test(FP ~ group2, detailed = T, paired = F) 
write.csv(df_p_val, file = "Results/Stats/mann_whitney_FP_by_tissue_reinf3_timeline.csv")


#supp table 12#
df_p_val <- subset(reinf3_df, INPUT2 != OUTPUT2 & group %in% c("2reinf_2wk", "1single_12wk")) %>%
  rstatix::group_by(OUTPUT3, INPUT3) %>% 
  rstatix::wilcox_test(FP ~ group2, detailed = T, paired = F) 
write.csv(df_p_val, file = "Results/Stats/mann_whitney_FP_by_tissue_reinf3_reinfections_compared_to_single.csv")


#reinfection analysis#

#skin to viscera#
ggplot(subset(reinf3_df, INPUT2 != OUTPUT2 & group %in% c("2reinf_2wk", "1single_12wk") & INPUT3 %in% c("SKIN") & OUTPUT3 != "SKIN"), 
       aes(y= log(FP), x = group)) + 
  geom_jitter(aes(colour = group, shape = as.factor(mouse_ID), group = as.factor(mouse_ID)),
              size = 2.5, stroke = 2,
              position = position_jitterdodge(dodge.width = .75, jitter.width = 0.1)) + 
  geom_boxplot(aes(fill = group), alpha = 0.3,
               outlier.shape = NA, 
               width = 0.75, lwd = 0.8, fatten = 2, show.legend = FALSE) +
  scale_shape_manual(values = c(15, 16, 17, 18, 19, 8, 15, 16, 17,18,19)) +
  labs(title = "Viscera seeding from skin\n", colour = "Group:", x= "\nGroup", y = "log(TSFP)\n") +
  scale_y_continuous(expand = expansion(mult = c(0, .2))) +
  #scale_x_discrete(expand = expansion(mult = c(0.15, 0))) +
  scale_x_discrete(labels = c("Single", "RI 2wk")) +
  theme_bw() + theme(legend.title = element_text(size = 18, hjust = 0.5),
                     plot.title = element_text(hjust = 0.5, size = 26),
                     legend.title.position = "top",
                     legend.position = "bottom",
                     panel.border = element_blank(), 
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     axis.title = element_text(size=28), 
                     axis.line = 
                       element_line(colour = "black"), 
                     axis.text.x = element_text(size = 20, colour = "black"),
                     axis.text.y = element_text(size = 20, colour = "black"),
                     legend.text = element_text(size = 16, colour = "black"),
                     strip.text.x = element_text(size = 20)) +
  scale_fill_manual(values = c("#440154","#35b779"), labels = c("Single Infection", "Re-infection 2 weeks")) +
  scale_colour_manual(values = c("#440154","#35b779"), labels = c("Single Infection", "Re-infection 2 weeks")) +
  #scale_fill_manual(values = c("#21918c", "#3b528b", "#440154"), labels = c("4 weeks", "10 weeks", "12 weeks")) +
  #scale_colour_manual(values = c("#21918c", "#3b528b", "#440154"), labels = c("4 weeks", "10 weeks", "12 weeks"))+
  guides(fill="none", shape = "none", colour = "none") +
  stat_pwc(aes(y=log(FP), x=group, group = group),
           hide.ns = "p", vjust = -0.25, step.increase = 0.15,
           bracket.nudge.y = 0.1, tip.length = 0, size = 0.5, label.size = 5, label = "p", 
           method = "wilcox_test")
ggsave(paste0(file = "Results/Figures_for_paper/reinf3_FP_by_tissue_skin_input_plot_reinfections_amalgamated.png"), height = 6, width=6)
ggsave(paste0(file = "Results/Figures_for_paper/reinf3_FP_by_tissue_skin_input_plot_reinfections_amalgamated.pdf"), height = 6, width=6)


#skin to skin#
ggplot(subset(reinf3_df, INPUT2 != OUTPUT2 & group %in% c("2reinf_2wk", "1single_12wk") & INPUT3 %in% c("SKIN") & OUTPUT3 %in% c("SKIN")), 
       aes(y= FP, x = group)) + 
  geom_jitter(aes(colour = group, shape = as.factor(mouse_ID)),
              size = 2.5, stroke = 2,
              position = position_jitterdodge(dodge.width = .75, jitter.width = 0.1)) + 
  scale_shape_manual(values = c(15, 16, 17, 18, 19, 8, 15, 16, 17,18,19)) +
  labs(title = "Skin to skin seeding\n", colour = "Mouse:", x= "\nGroup", y = "TSFP\n") +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  #scale_x_discrete(expand = expansion(mult = c(0.15, 0))) +
  scale_x_discrete(labels = c("Single", "RI 2wk")) +
  theme_bw() + theme(legend.title = element_text(size = 18, hjust = 0.5),
                     plot.title = element_text(hjust = 0.5, size = 30),
                     legend.title.position = "top",
                     legend.position = "bottom",
                     panel.border = element_blank(), 
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     axis.title = element_text(size=28), 
                     axis.line = 
                       element_line(colour = "black"), 
                     axis.text.x = element_text(size = 20, hjust = 0.5, colour = "black"),
                     axis.text.y = element_text(size = 20, colour = "black"),
                     legend.text = element_text(size = 16, colour = "black"),
                     strip.text.x = element_text(size = 20)) +
  scale_fill_manual(values = c("#440154","#35b779"), labels = c("Single Infection", "Re-infection 2 weeks")) +
  scale_colour_manual(values = c("#440154", "#35b779"), labels = c("Single Infection", "Re-infection 2 weeks")) +
  guides(fill="none", shape = "none", colour = "none") +
  stat_pwc(aes(y=FP, x=group, group = group),
           hide.ns = "p", vjust = -0.25, step.increase = 0.15,
           bracket.nudge.y = 0.1, tip.length = 0, size = 0.5, label.size = 5, label = "p", 
           method = "wilcox_test")
ggsave(paste0(file = "Results/Figures_for_paper/reinf3_FP_by_tissue_skin_to_skin_reinfections.png"), height = 6, width=6)
ggsave(paste0(file = "Results/Figures_for_paper/reinf3_FP_by_tissue_skin_to_skin_reinfections.pdf"), height = 6, width=6)



ggplot(subset(reinf3_df, INPUT2 != OUTPUT2 & group %in% c("2reinf_2wk", "1single_12wk") & INPUT3 %in% c("SKIN") & OUTPUT3 != "SKIN"), 
       aes(y= FP, x = group)) + 
  geom_jitter(aes(colour = group, shape = as.factor(mouse_ID)),
              size = 2.5, stroke = 2,
              position = position_jitterdodge(dodge.width = .75, jitter.width = 0.1)) + 
  geom_boxplot(aes(fill = group), alpha = 0.3,
               outlier.shape = NA, 
               width = 0.75, lwd = 0.8, fatten = 2, show.legend = FALSE) +
  scale_shape_manual(values = c(15, 16, 17, 18, 19, 8, 15, 16, 17,18,19)) +
  labs(title = "Tissue-sourced seeding from skin\n", colour = "Group:", x= "\nGroup", y = "TSFP\n") +
  scale_y_continuous(expand = expansion(mult = c(0, .2))) +
  #scale_x_discrete(expand = expansion(mult = c(0.15, 0))) +
  scale_x_discrete(labels = c("Single", "RI 2wk")) +
  theme_bw() + theme(legend.title = element_text(size = 18, hjust = 0.5),
                     plot.title = element_text(hjust = 0.5, size = 30),
                     legend.title.position = "top",
                     legend.position = "bottom",
                     panel.border = element_blank(), 
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     axis.title = element_text(size=28), 
                     axis.line = 
                       element_line(colour = "black"), 
                     axis.text.x = element_text(size = 20, hjust = 1, angle = 45, colour = "black"),
                     axis.text.y = element_text(size = 20, colour = "black"),
                     legend.text = element_text(size = 16, colour = "black"),
                     strip.text.x = element_text(size = 20)) +
  scale_fill_manual(values = c("#440154","#35b779"), labels = c("Single Infection", "Re-infection 2 weeks")) +
  scale_colour_manual(values = c("#440154", "#35b779"), labels = c("Single Infection", "Re-infection 2 weeks"))+
  #scale_fill_manual(values = c("#21918c", "#3b528b", "#440154"), labels = c("4 weeks", "10 weeks", "12 weeks")) +
  #scale_colour_manual(values = c("#21918c", "#3b528b", "#440154"), labels = c("4 weeks", "10 weeks", "12 weeks"))+
  guides(fill="none", shape = "none") +
  #stat_pwc(aes(y=FP, x=group, group = group),
  #       hide.ns = "p", vjust = -0.25, step.increase = 0.15,
  #       bracket.nudge.y = 0.1, tip.length = 0, size = 0.5, label.size = 5, label = "p", 
  #       method = "wilcox_test")  +
  facet_wrap(~OUTPUT3, nrow = 2, scales = "free", labeller = as_labeller(
    c(BM = "Bone Marrow", GUT = "Gut", LIVER = "Liver", LN =  "Lymph Node", LUNG = "Lung", S = "Spleen", SKIN = "Skin")))
ggsave(paste0(file = "Results/Figures_for_paper/reinf3_FP_by_tissue_skin_input_plot_reinfections_FINAL.png"), height = 10, width=8)
ggsave(paste0(file = "Results/Figures_for_paper/reinf3_FP_by_tissue_skin_input_plot_reinfections_FINAL.pdf"), height = 10, width=8)

ggplot(subset(reinf3_df, INPUT2 != OUTPUT2 & group %in% c("2reinf_2wk", "1single_12wk") & OUTPUT3 %in% c("SKIN") & INPUT3 != "SKIN"), 
       aes(y= FP, x = group)) + 
  geom_jitter(aes(colour = group, shape = as.factor(mouse_ID)),
              size = 2.5, stroke = 2,
              position = position_jitterdodge(dodge.width = .75, jitter.width = 0.1)) + 
  geom_boxplot(aes(fill = group), alpha = 0.3,
               outlier.shape = NA, 
               width = 0.75, lwd = 0.8, fatten = 2, show.legend = FALSE) +
  scale_shape_manual(values = c(15, 16, 17, 18, 19, 8, 15, 16, 17,18,19)) +
  labs(title = "Tissue-sourced seeding to skin\n", colour = "Group:", x= "\nGroup", y = "TSFP\n") +
  scale_y_continuous(expand = expansion(mult = c(0, .2))) +
  #scale_x_discrete(expand = expansion(mult = c(0.15, 0))) +
  scale_x_discrete(labels = c("Single", "RI 2wk")) +
  theme_bw() + theme(legend.title = element_text(size = 18, hjust = 0.5),
                     plot.title = element_text(hjust = 0.5, size = 30),
                     legend.title.position = "top",
                     legend.position = "bottom",
                     panel.border = element_blank(), 
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     axis.title = element_text(size=28), 
                     axis.line = 
                       element_line(colour = "black"), 
                     axis.text.x = element_text(size = 20, angle = 45, hjust = 1, colour = "black"),
                     axis.text.y = element_text(size = 20, colour = "black"),
                     legend.text = element_text(size = 16, colour = "black"),
                     strip.text.x = element_text(size = 20)) +
  scale_fill_manual(values = c("#440154","#35b779"), labels = c("Single Infection", "Re-infection 2 weeks")) +
  scale_colour_manual(values = c("#440154", "#35b779"), labels = c("Single Infection", "Re-infection 2 weeks"))+
  #scale_fill_manual(values = c("#21918c", "#3b528b", "#440154"), labels = c("4 weeks", "10 weeks", "12 weeks")) +
  #scale_colour_manual(values = c("#21918c", "#3b528b", "#440154"), labels = c("4 weeks", "10 weeks", "12 weeks"))+
  guides(fill="none", shape = "none") +
  #stat_pwc(aes(y=FP, x=group, group = group),
  #         hide.ns = "p", vjust = -0.25, step.increase = 0.15,
  #         bracket.nudge.y = 0.1, tip.length = 0, size = 0.5, label.size = 5, label = "p", 
  #         method = "wilcox_test")  +
  facet_wrap(~INPUT3, nrow = 2, scales = "free", labeller = as_labeller(
    c(BM = "Bone Marrow", GUT = "Gut", LIVER = "Liver", LN =  "Lymph Node", LUNG = "Lung", S = "Spleen", SKIN = "Skin")))
ggsave(paste0(file = "Results/Figures_for_paper/reinf3_FP_by_tissue_skin_output_plot_reinfections_FINAL.png"), height = 10, width=8)
ggsave(paste0(file = "Results/Figures_for_paper/reinf3_FP_by_tissue_skin_output_plot_reinfections_FINAL.pdf"), height = 10, width=8)
